# Generated by Django 2.2.4 on 2019-10-17 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0024_auto_20180110_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 18, 46, 35, 388793, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
